### ISSUE TITLE
Corrupted Serial upload to SD card

### ISSUE THREAD

**Issue by theman00011** [luc-github/ESP3D#251] opened 2018-09-22 01:37 UTC
I've been trying to upload and print a gcode file in 8.3 format, but every time I upload a file, it never shows up in the files list. If I run a M20 command, sometimes it shows the file on the SD card but I'm unable to run it. If I try to run M23 <FILENAME> it returns 
`Error:Line Number is not Last Line Number+1, Last Line: 0
Resend: 1`

Other times I just get `upload failed`. Not sure if it is related but when I select a file to upload, the progress bar immediately skips to 100% and sticks there for a couple minutes while it attempts to upload I believe.
I've tried both 2.0 dev and am currently on 1.0 with no success running on Marlin firmware.

Also, this happened one time. https://imgur.com/a/gJLRG7j

EDIT: G-code appeared corrupt because Marlin stripped the comments, changing the size and hash.

**Comment by theman00011** [comment] 2018-09-22 08:58
Yes, right now it is an uploading issue but the couple times I did get a print to start, it was very erratic and just grinded the filament at max speed until I shut it down. I am almost certain the gcode is good but we can cross that when we get there.

I tried 1.0, 2.0, 2.1 and 2.0 with async & async UI without success. 

I believe the picture was on 1.0 but it's possible I'm wrong.

Marlin version is 1.0.0

Baud rate I use is 250000

The only thing plugged into the printer is the SD card.

**Comment by luc-github** [comment] 2018-09-22 09:07
For printing ESP3D has nothing to do with printing process - it just launchs SD  print command to Marlin - print is 100% handled by Marlin 

if you says GCODE is correct on SD then it is not ESP3D issue - the Upload can be, but printing no, once print is launched it is out of ESP3D.

You can verify that by manually copy GCODE file to SD and print from SD from printer then launch another print from ESP3D to compare.

Can you give me the exact version of Marlin you use?

I will try to see if there was some change since I tested and try again - Marlin code is always changing and I do not really always follow the changes in real time as I do not used Marlin

**Comment by theman00011** [comment] 2018-09-22 09:51
This is the output of M115
`FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:https://github.com/ErikZalm/Marlin/ PROTOCOL_VERSION:1.0 MACHINE_TYPE:ROBOR1PLUSV2 EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000`

I reformatted the SD card as FAT instead of FAT32 to see if that makes any difference. I'm currently doing a upload test with Simplify3D to make sure that works as expected. (It's so slowwww) If so, I'll plug in the ESP8266 and try it again.

**Comment by luc-github** [comment] 2018-09-22 11:05
This FW is pretty old I am surprised ESP3D can list files properly - I will do some tests on a system to check

**Comment by theman00011** [comment] 2018-09-22 11:37
That bug you linked in the Marlin repo looks very similar to my problem but I am on a much older version and that is a problem with a recent commit. I dug into my Marlin firmware and found the only place that error is called is the get_command function in Marlin_main.cpp if you want to see the code that throws the error. The line that throws that error is `SERIAL_ERRORPGM(MSG_ERR_LINE_NO);`

**Comment by luc-github** [comment] 2018-09-22 11:42
Yes but at that time I had no info about your FW version. I was guessing with info I had

**Comment by theman00011** [comment] 2018-09-22 11:56
Right. Is it possible to put the g-code in the SPIFFS filesystem and just stream the commands to the printer from the ESP8266? It would save a lot of time from not having to put the g-code on the printers SD card.

**Comment by theman00011** [comment] 2018-09-22 11:58
Also, the problem picture I linked to in the original post happened again with a fresh install of 2.0. I started ESP3D, made sure the SD was clear, started the upload, it stayed at 100% for about a minute and a half (Way too short for the full upload), and then it started trying to erratically print automatically and the files box was filled with temperature data.

**Comment by theman00011** [comment] 2018-09-22 23:49
Update: I upgraded to Marlin 1.1.9 and the problem is still there. Uploaded a file, progress bar started at 70%, progressed to 100% in a minute or so before starting printing automatically and erratically so it isn't unique to that firmware version. This is the new output of M115.

`FIRMWARE_NAME:Marlin bugfix-1.1.x (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Robo R1+ EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:EEPROM:1
Cap:VOLUMETRIC:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:1
Cap:Z_PROBE:1
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:0
Cap:AUTOREPORT_SD_STATUS:0
Cap:THERMAL_PROTECTION:1`

**Comment by luc-github** [comment] 2018-09-23 07:46
The print start automaticaly ? that is weird, it means the commands are not saved to SD but send to printer

Can you share the file you said it is only  310KB

**Comment by theman00011** [comment] 2018-09-23 07:55
Sure, it's attached. That's why I have the theory that ESP3D thinks it is still uploading but in reality, it has exited save mode for some reason and is in normal mode.


[openlock.zip](https://github.com/luc-github/ESP3D/files/2408523/openlock.zip)

**Comment by luc-github** [comment] 2018-09-23 08:13
thank you I have setup a system - just need to flash the Marlin FW on it - so I will have a look today

**Comment by theman00011** [comment] 2018-09-23 08:17
Sounds good. I thought the firmware update would fix it but I guess now. (Also, the new auto bed leveling is so awesome, I'm glad I decided to upgrade Marlin. The 1.0.0 bed leveling didn't do much.)

**Comment by luc-github** [comment] 2018-09-23 12:37
Can reproduce issue with ESPD2.0  : 
after 3min upload I got :  
```
Error:No Checksum with line number, Last Line: 0
Resend: 1
```
so no line was accepted

![image](https://user-images.githubusercontent.com/8822552/45928072-db6c0580-bf3d-11e8-80b9-b18f1a87d46b.png)

what ever I type I got same message:
```
M29
Error:No Checksum with line number, Last Line: 0
Resend: 1
```

need to check how to reset this - a part of restart printer board

**Comment by luc-github** [comment] 2018-09-23 12:43
and of course :
```
M20
Begin file list
OPENLOCK.GCO 0
End file list
```

**Comment by theman00011** [comment] 2018-09-23 12:47
Great, at least it is reproducible. Not sure what is causing it though and why it's only a problem I've run into.

**Comment by luc-github** [comment] 2018-09-23 12:53
I think it is not same issue as you got initialy 
if I comment lines as suggested in link above I get :
![image](https://user-images.githubusercontent.com/8822552/45928213-7239c180-bf40-11e8-88b6-5c145e842419.png)

Now I will check file integrity

**Comment by theman00011** [comment] 2018-09-23 13:00
Comment which lines? Because in the Marlin link you sent, that is for a recent build and they suggest to comment some lines in queue.cpp which doesn't exist in either version of Marlin that I tested with.

**Comment by luc-github** [comment] 2018-09-23 13:04
yes not same file:

![image](https://user-images.githubusercontent.com/8822552/45928299-96e26900-bf41-11e8-87f5-5e909174b2c3.png)

Stripping look correct at first glance :

![image](https://user-images.githubusercontent.com/8822552/45928290-83370280-bf41-11e8-9994-b771daf7f566.png)

but actually some parts are corrupted:
![image](https://user-images.githubusercontent.com/8822552/45928312-d7da7d80-bf41-11e8-9d12-526753d96b16.png)

I will try to see if corruption come from upload part or serial transfert part

**Comment by theman00011** [comment] 2018-09-23 13:06
Ah, okay. How hard would it be to implement a checksum compatible with Marlin that could be toggled? Since it appears the checksum is needed or it is possible to get a corrupt print.

**Comment by luc-github** [comment] 2018-09-23 13:10
Implement check sum is not really hard:
1 - before upload launch M110 N0
2 - for each line do checksum
This will slow down more the transfert

but before that I need to be sure upload is correct, because if upload is corrupted checksum will be Ok as done on ESP3D side with wrong content

**Comment by luc-github** [comment] 2018-09-23 13:12
On your side I suggest you to check your slicer - line 27 is not correct

**Comment by luc-github** [comment] 2018-09-23 13:46
Ok Upload is correct 
so issue is either in stripping method or in Serial transfert - I check

**Comment by luc-github** [comment] 2018-09-23 14:04
So far my stripping is correct (I am relieved ^_^)

So time to implement checksum and line numbering for test

**Comment by luc-github** [comment] 2018-09-23 19:09
Ok I have a test code working but I need to fine tune several parts
the issue is not generating checksum
the issue is catch error properly
Unlike Repetier, Marlin validate command with `ok` without line numbering
So need to guess which `ok` is for what command or you get discrepancy when  check sum error happen
for example : checksum error is on line 250 but you already sent 260 lines..., hard to rollback ...

Anyway I got on download Ok - may be by luck so I need to test more and adjust some serial buffer purge

Will continue on it tomorrow

**Comment by theman00011** [comment] 2018-09-23 20:53
`{travel_speed}` is still shown as available in the Cura definitions for some printers so I would assume it is still a valid variable unless some of the docs just aren't updated.

Were you able to successfully implement the checksum and line numbering?

**Comment by luc-github** [comment] 2018-09-24 12:15
Well if variable is not replaced then there is an issue - printer does not understand `{travel_speed}`

Yes, it is implemented, I have uploaded test file several times successfuly,  I am even able to upload 1.3MB file without error:
![image](https://user-images.githubusercontent.com/8822552/45951201-e2108080-c002-11e8-9449-fdf332f1567d.png)

But I need to strees more, because I got at the begining, several times, an issue with Marlin FW but I am not able to reproduce now:
when start using M28
normal output is (this is without checksum /numbering for demo):
```
M28 /test.gco
echo:Now fresh file: /test.gco
Writing to file: /test.gco
ok
```
but I got several times :
```
M28 /test.gco
ok
```
so file is not created and following commands to be saved are actually seen as direct command

I need to check now repetier / smoothieware / MarlinKimbra to verify if I can secure such issue as for now I only check `ok` answer

**Comment by luc-github** [comment] 2018-09-24 18:19
Repetier is now properly tuned :
communication is easier to handle but need to handle extra answer `wait` so cannot really purge serial as always have `wait`
```
Purge Serial


wait
wait

Purge Serial
N5836 G1 X112 Y152 E1073.97502*98
ok 5836

got ok
Purge Serial
Purge Serial
N5837 G1 X112 Y144.45 E1074.39364*78
ok 5837

got ok
Purge Serial
Purge Serial
N5838 G1 X116 Y144.45 E1074.61543*75
ok 5838

```
also sometime the number come after the `ok` so need to cummulate answers to handle properly:
```
N432 G0 F3600 X131.877 Y146.019*78
ok  <- first part not recognised because no line number
ok 432 -<first part + second part

got ok <- ok + line number is recognised
```
I need to redo Marlin with latest code  then Marlin Kimbra  and Smoothieware

**Comment by luc-github** [comment] 2018-09-24 19:33
For Marlin currently it need to comment :
```
#if ENABLED(SDSUPPORT)
        else if (card.saving) {
          gcode_line_error(PSTR(MSG_ERR_NO_CHECKSUM));
          return;
        }
      #endif
```
because M29 should not use checksum/line number or you cannot recover

**Comment by luc-github** [comment] 2018-09-24 20:32
Looks like Marlin Kimbra has same issue

**Comment by luc-github** [comment] 2018-09-25 07:02
Smoothieware does not have such issue but reset Numbering seems working only once

**Comment by theman00011** [comment] 2018-09-25 07:08
There must be a way to do it in ESP3D to fix it since Simplify3D was able to upload just fine without editing Marlin, which I would rather not have to do.

**Comment by luc-github** [comment] 2018-09-26 09:56
Ok for smoothieware documentation is wrong the correct syntax to reset is :
```
N{New Line Position} M110
```
so need to adjust code to follow :
1 - smoothieware 
which is quiet (no` wait` when idle), use `N{New Line Position} M110` to reset, and resend error is `rs <line number>`, `M29` does not need checksum, send `ok` without line number

2 - Marlin Kimbra
which is not quiet (send `wait` when idle), use `N{New Line Position} M110` to reset, resend error is `Resend:<line number>` ,  `M29`  need checksum,  `ok` does not use line number

3 - Marlin 
which is quiet (no `wait` when idle), use `N{New Line Position} M110` to reset, resend error is `Resend:<line number>` ,  `M29`  need checksum,  `ok` does not use line number

4 - Repetier
which is not quiet (send `wait` when idle), use `N{New Line Position} M110` to reset, resend error is `Resend:<line number>` ,  `M29`  does not need checksum,  `ok` use line number

**Comment by luc-github** [comment] 2018-09-26 12:11
additionally I will add a detection in close function using M29 to catch what is the expected number, in case of issue, and use this number / checksum for M29, this will be also added to an [ESP4XX] command to clear any faulty upload manualy - so all situations should be handled

**Comment by luc-github** [comment] 2018-10-03 07:05
I am travelling right now, so this slow down a bit my availability to code
I have already identified almost all impact/actions to be done, still need to see about async webserver but will start with sync because better not to use async on ESP3D with ESP8266 currently
So should have some code update soon - I hope

**Comment by luc-github** [comment] 2018-10-28 17:08
I am back and will work on it this week - sorry for the delay but vacations make me busy  ^_^

**Comment by AdrienHunter** [comment] 2018-10-28 18:41
Many thanks for your status update, right in time as my new printer will be ready soon :-) Appreciate your work there. For me, except of the SD-Card upload, everything else is working fine :-)

**Comment by luc-github** [comment] 2018-10-30 19:39
Code is done and I am now testing it -  for some reason M110 N0 seems not working during my tests on Marlin Kimbra - so I changed the approach, instead of resetting the line number, I do a line number detection using a preleminary  `N1 M29 Nx` command to get the correct expected line number send back by error message. 
Doing like this I am able to do several upload without issue

I will update my marlin / marlin Kimbra / repetier / smoothieware system tests with latest FW and check the fix, if Ok I will push the code to repo

**Comment by luc-github** [comment] 2018-10-31 16:51
For repetier there are 2 cases : 
`Resend:XXX` and `skip XXX` 
Resend:XXX is used when checksum is incorrect and skip XXX is used when Numbering is incorrect...

**Comment by luc-github** [comment] 2018-11-01 20:22
Ok after some runs on different FW I reach a working way for upload
1 - closing with M29 and checksum and line numbering detection, for repetier if failed do M29 without checksum
if failed abort upload
2 - Reset line numbering to 0
if failed abort upload
3 - Send M28 command with line 1 and check sum
no autodection of line numbering as defined by reset
if failed abort upload
4 - send each line with incremented line number and checksum
no autodection of line numbering as defined by reset
if failed abort upload
5 - send M29 with line numbering and checksum 
if failed for repetier do M29 without line numbering/checksum

So it should cover all case, the trickiest is repetier as more test case than others FW
So far so good
Need to pass all FW test and should be Ok

**Comment by theman00011** [comment] 2018-11-03 05:47
Trying to upload a gcode in 8.3 format I get 
`    Error 0 : `
and no gcode file ever appears

Even worse, every 10 or so seconds I get
`Connection lost for more than 20s`

When using the latest 2.1 webui .gz file and no gcode file ever shows up.

Also, the printer seems to be getting spammed with debug information.
![image](https://user-images.githubusercontent.com/31234646/47948617-09137980-df02-11e8-88a1-6ec845e75775.png)

**Comment by luc-github** [comment] 2018-11-03 07:29
why did you updated to Web-UI 2.1 ? the Fix in in ESP3D firmware not in WebUI
ESP3D 2.1 has a heartbeat feature but it is not in public repo,  only on GRBL_ESP32 repo, this what you seem, to disable it go to WebUI preferences and disable monitoring.

Please confirm your Marlin Version and your ESP3D Version

**Comment by theman00011** [comment] 2018-11-03 07:42
Because it was the only UI that had an index.html.gz file updated in the past 5 months. Which UI should I be using?

ESP3D: `UI: 2.1b8 / FW: 2.0.0.c21`
Marlin: Marlin bugfix-1.1.x

**Comment by luc-github** [comment] 2018-11-03 07:42
But good catch seems WebSocket do debug message and it is not disabled by default -
 it is weird I do not have it on my side

**Comment by luc-github** [comment] 2018-11-03 07:45
can you give Marlin version ? not branch 
I tested on Marlin 1.1.9

**Comment by luc-github** [comment] 2018-11-03 07:54
Also what size of the file you upload - so I can reproduce

**Comment by theman00011** [comment] 2018-11-03 08:04
I believe it's on Marlin-bugfix-1.1.9 since that is what is in my Arduino library. M115 just gives Marlin bugfix-1.1.x

I downgraded to 2.0 to fix the disconnecting problem but that still leaves the debug message spam and upload error. The file is only 310KB and it's the same error on UI 2.0.

**Comment by luc-github** [comment] 2018-11-03 08:28
Debug message come from Websocket library - I just pushed a commit disable it in code and websocket library itself - can you give a try to see if you still have these debug message - I cannot see them

I just uploaded a 1.16MB file on Marlin 1.1.9 - 1.1.9 was released 2 month ago (31th July)  so bug fix 1.1.X should identical as last update was 1 month ago - this is the one you use ?

Did you do any specifics settings for SD in configuration ?

**Comment by luc-github** [comment] 2018-11-03 08:33
I am guessing the issue come from the debug message not Marlin - so in theory once no more debug output it should be Ok
I have enclosed my 2 tests files to verify also issue do not come from unexpected line in GCODE file
[test.zip](https://github.com/luc-github/ESP3D/files/2544758/test.zip)

**Comment by theman00011** [comment] 2018-11-03 08:51
Still getting the debug messages on version UI: 2.0c30 / FW: 2.0.0.c22

**Comment by luc-github** [comment] 2018-11-03 08:54
did you updated the arduinoWebSockets library ?

**Comment by theman00011** [comment] 2018-11-03 08:59
It's version 2.2.1

**Comment by luc-github** [comment] 2018-11-03 09:05
In theory should be 2.1.2 so I am not sure where this 2.2.1 come from.

Anyway as wrote in my readme, please use the one in my repo.
Also just now I have just hard coded the define to be sure is not enabled
![image](https://user-images.githubusercontent.com/8822552/47950248-cd9f9c00-df4f-11e8-845f-fb9a630794da.png)

**Comment by theman00011** [comment] 2018-11-03 09:10
I meant 2.1.1 and edited it after

**Comment by luc-github** [comment] 2018-11-03 09:14
please use the one from my repo - it is the 2.1.2 with also the `#define NODEBUG_WEBSOCKETS` to be sure

**Comment by theman00011** [comment] 2018-11-03 09:30
Using the libraries in the repo fixed the debug problem. You might want to mention that in the install instructions since I don't see anywhere where it says to copy those libraries over. 

But I still get the `Error 0 :` with your files.

**Comment by luc-github** [comment] 2018-11-03 09:39
https://github.com/luc-github/ESP3D/tree/2.0#installation but there are some typo 

I do not get it - i woks on my side

**Comment by theman00011** [comment] 2018-11-03 09:46
Yeah, I'm not sure. Everything else seems to work, I can send commands and all but I can't upload files. Is it supposed to be uploading them to SPIFFS or to the printer SD card?

**Comment by luc-github** [comment] 2018-11-03 09:49
last way to check : 
in config.h enable debug and SPIFFS serial
![image](https://user-images.githubusercontent.com/8822552/47950669-a2b84680-df55-11e8-9dc5-5d84db13673a.png)

1 - flash the ESP
2 - upload the t1.g I sent you
it is 1 line of GCODE - it is enough to check
3 - once failed go to ESP3D FS and download log.txt
![image](https://user-images.githubusercontent.com/8822552/47950688-f88cee80-df55-11e8-8824-348bdbbb29c4.png)

send to me the log.txt

**Comment by luc-github** [comment] 2018-11-03 09:50
The upload is on SD card

**Comment by theman00011** [comment] 2018-11-03 10:02
[log.txt](https://github.com/luc-github/ESP3D/files/2544844/log.txt)

Here's the log

**Comment by theman00011** [comment] 2018-11-03 10:05
Here's the log when connected to printer

[log2.txt](https://github.com/luc-github/ESP3D/files/2544849/log2.txt)

**Comment by luc-github** [comment] 2018-11-03 10:09
On log you are not connected as no command works
On log 2 I see no error -  the upload raise no error

**Comment by luc-github** [comment] 2018-11-03 10:13
Can you confirm - no error raised ?
I see the file t1.g does not appear in SD content

is that correct ?

**Comment by theman00011** [comment] 2018-11-03 10:28
Here is the relevant log. In it I try to upload without M20 first, and it fails, then I do M20 and I upload successfully. 
[log 3.txt](https://github.com/luc-github/ESP3D/files/2544877/log.3.txt)

**Comment by luc-github** [comment] 2018-11-03 10:40
M21 is supposed to init SD card - if your FW do not do it you won't have access to SD 
M21 is not done by ESP3D - it is supposed to be done by Marlin when SD Detect pin is defined or by user if no SD Detect pin is available

**Comment by theman00011** [comment] 2018-11-03 10:42
I don't think a lot of printers have the SD detect to automatically init because in the Simplify3D upload implementation, it sends M21 to init the card before it starts sending as well.

**Comment by theman00011** [comment] 2018-11-03 10:43
Though I think there is still a problem because I get the Error 0 when using any of my files, even ones that aren't very big.

**Comment by luc-github** [comment] 2018-11-03 10:45
I can add it but this is definitly an ugly patch 
what is you printer model ?

**Comment by theman00011** [comment] 2018-11-03 10:46
ROBO 3D R1+

**Comment by luc-github** [comment] 2018-11-03 10:49
I guess you modified FW to put Marlin 1.X ?

**Comment by theman00011** [comment] 2018-11-03 10:50
Yeah, I updated when I was first having this problem since I wanted to make sure it wasn't just a problem with the old FW. I just grabbed the new version off the forums.

**Comment by luc-github** [comment] 2018-11-03 10:55
Yes for what I can see they did not put SD Detect Pin in FW when it is should be in original FW as it make no sense to have a SDCard reader and mount manually

For big file issue I need 
1 - format SD using the tool from www.sdcard.org
2 - The log to see what is the error when it happen as on my side I cannot reproduce

**Comment by theman00011** [comment] 2018-11-03 11:18
So here's what I did:

1. Formatted the SD card with the tool
2. Started printer and did M21 to init SD card
3. Started upload of file
4. Waited ~15 minutes while the progress bar stayed at 100%
5. Refreshed the page and got Error 0
6. Everything hangs and page stops loading

I don't see any errors so maybe I just need to leave it for like an hour? But it is only 310KB so it's hardly a big file. I can send it to you if you want and you can see if the same thing happens to you.
[log 4.txt](https://github.com/luc-github/ESP3D/files/2544902/log.4.txt)

**Comment by luc-github** [comment] 2018-11-03 11:33
Yes you reset your board when it was still uploading - Serial Upload is slow like hell
Unfortunalty the progress bar means everything was sent but it will stay until everything is actually wrote on SD
please share the file I can check how long it take to upload

**Comment by theman00011** [comment] 2018-11-03 11:39
I might just stick to manually putting it on the SD card then. It would be nice if you could upload it to SPIFF on ESP and then run the file from there like I think the Raspberry Pi does. Then it is just like a USB print and the printer SD never even sees the file.

[openlock.zip](https://github.com/luc-github/ESP3D/files/2544914/openlock.zip)

**Comment by luc-github** [comment] 2018-11-03 11:51
I use toshiba flash air wifi SD card  it is really nice and allows fast upload
Will check your file

**Comment by luc-github** [comment] 2018-11-03 12:09
I have uploaded your file in 5 min, my baud rate is 250000

Looking at your log you stopped upload at : line 1236 when your file has more than 11K lines
the log show no error time out so may be increasing baud rate will help, it also depend of printer processor speed but there is not error so far on your log even no time out - it is just slow like hell

**Comment by theman00011** [comment] 2018-11-03 12:11
I am using 250000 as well though

**Comment by luc-github** [comment] 2018-11-03 12:19
I can add some timestamp to see what part is slow - as you do use modified Marlin for Robo3D R1 it may have something that I cannot see on my side

**Comment by theman00011** [comment] 2018-11-03 12:20
Possibly, and timestamps would be nice to troubleshoot. I am running now to see how long it takes. So far it's been about 9 minutes.

**Comment by luc-github** [comment] 2018-11-03 12:48
I have added time stamp for purge and sendLine2Serial and testing now - it is as slow as you I think as after 5 min I am still at 10% 
so this is definitly due to LOG to SPIFFS slowing down the whole upload -

**Comment by theman00011** [comment] 2018-11-03 12:49
Yeah, 40 minutes later and it still shows uploading. I'll try disabling debug later today.

**Comment by theman00011** [comment] 2018-11-04 09:07
So disabling debug seemed to fix the upload time problem and that file uploaded in about 5 minutes, same as you. Also, the diff on the uploaded file and original looked correct, just with all the comments removed so it looks like everything was written properly on first look.

**Comment by luc-github** [comment] 2018-11-04 09:42
Hmmm no I do not log wifi password - only SSID
this is what I log in setup :
```
Set STA mode
SSID NETGEAR_2GEXT_OFFICE2
Setup Done
```

**Comment by theman00011** [comment] 2018-11-04 09:44
It was definitely in there. It was only on the first setup though when you set all your settings and pick a wifi network and enter your password.

**Comment by luc-github** [comment] 2018-11-04 09:45
you mean doing 1st wizard ?

**Comment by theman00011** [comment] 2018-11-04 09:45
Yes

**Comment by luc-github** [comment] 2018-11-04 09:48
I see, this is when you update any EEPROM settings the function save data is generic it does not know it what it is

**Comment by luc-github** [comment] 2018-11-04 09:55
back to M21 - your printer does have LCD ?
looking at code :
```
#if SDCARDDETECT == -1
static void lcd_sd_refresh()
{
    card.initsd();
    currentMenuViewOffset = 0;
}
#endif
```

**Comment by theman00011** [comment] 2018-11-04 10:56
No, it doesn't

**Comment by luc-github** [comment] 2018-11-04 12:48
Ok so the best is to put `card.initsd(); `in setup then - so when printer power on it will mount SD card automatically

**Comment by luc-github** [comment] 2018-11-04 13:41
I have added the M21 in serial upload process - https://github.com/luc-github/ESP3D/commit/3e38795c76f8aad0a5ae42561760bafc0d41511d

So I guess this issue can be closed now

**Closed by luc-github** 2018-11-04 13:41 UTC
Labels: ESP-2.X, Fixed, Marlin 1.0.X, bug

**Comment by tkuan** [comment] 2018-11-15 18:43
> 
> 
> Can reproduce issue with ESPD2.0 :
> after 3min upload I got :
> 
> ```
> Error:No Checksum with line number, Last Line: 0
> Resend: 1
> ```
> 
> so no line was accepted
> 
> ![image](https://user-images.githubusercontent.com/8822552/45928072-db6c0580-bf3d-11e8-80b9-b18f1a87d46b.png)
> 
> what ever I type I got same message:
> 
> ```
> M29
> Error:No Checksum with line number, Last Line: 0
> Resend: 1
> ```
> 
> need to check how to reset this - a part of restart printer board

I got the same problem when I upgraded to Marlin 1.1.9. There is a bugfix open for this, https://github.com/MarlinFirmware/Marlin/issues/11871. As I understand the issue is the new Marlin no longer taking straight text upload. It needs the line number and the checksum as described in the error in the latest Marlin. If I use Marlin 1.1.8, it works. To create one line "M106" of a gcode file, TEST.G, I will manually type "M28 TEST.G", "N0 M106*36"(not just "M106"), "M29" in ESP3D. It will save the file to the SD card.

**Comment by luc-github** [comment] 2018-11-15 19:05
If you check the bugfix comments - I am in it :wink: 
Now ESP3D 2.0 SD upload use Line number and check sum  - issue should not happen anymore

**Comment by tkuan** [comment] 2018-11-15 19:13
Thank you! I will check out the 2.0. I want to create a button in WebUI to control a relay to turn on/off the printer. I have followed your instructions to setup the development environment, but so far I can't install gulp on my Windows 7 computer. What is the best environment to use? Mac, PC or Linux?

**Comment by luc-github** [comment] 2018-11-15 19:21
I do it under windows and linux so I guess just stick to version I give OS is not important

**Comment by luc-github** [comment] 2018-11-15 20:05
But why not use Macro feature for your Button ?

**Comment by tkuan** [comment] 2018-11-15 20:21
I will love to use Macro, but not sure where to look for instructions.

**Comment by luc-github** [comment] 2018-11-15 20:30
I am not good at docs
but some people did : https://github.com/bdring/Grbl_Esp32/wiki/ESP3D-Web-UI-for-Grbl_ESP32#macros

Macro is just a link to a file with GCODE and [ESPXXX} commands

**Comment by tkuan** [comment] 2018-11-15 21:06
I think ESP command will work. I will check it out tonight. Thank you for your help.

**Comment by tkuan** [comment] 2018-11-16 16:07
I updated to 2.0 with 2.0 UI, but I can't see the Macro panel. How do I turn in on?

**Comment by luc-github** [comment] 2018-11-16 16:14
push Macro button
![image](https://user-images.githubusercontent.com/8822552/48633148-01a0a580-e9c3-11e8-89f8-bf2804fb3a21.png)

**Comment by tkuan** [comment] 2018-11-16 16:18
Got it! Thank you! I will try to power on/off this weekend.
